language: swift

osx_image: 
- xcode10
- xcode10.1
- xcode10.2
- xcode10.3
- xcode11
- xcode11.1
- xcode11.2
- xcode11.3

env:
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.2
- SWIFT_VERSION=5.0
- SWIFT_VERSION=5.1
- SWIFT_VERSION=5.2

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

matrix:
  exclude:
  - osx_image: xcode10
    env: SWIFT_VERSION=5.0
  - osx_image: xcode10
    env: SWIFT_VERSION=5.1
  - osx_image: xcode10
    env: SWIFT_VERSION=5.2
  - osx_image: xcode10.1
    env: SWIFT_VERSION=5.0
  - osx_image: xcode10.1
    env: SWIFT_VERSION=5.1
  - osx_image: xcode10.1
    env: SWIFT_VERSION=5.2
  - osx_image: xcode10.2
    env: SWIFT_VERSION=5.1
  - osx_image: xcode10.2
    env: SWIFT_VERSION=5.2
  - osx_image: xcode10.3
    env: SWIFT_VERSION=5.1
  - osx_image: xcode10.3
    env: SWIFT_VERSION=5.2

script:
  - xcodebuild clean build -scheme 'Adhan-watchOS' -project Adhan.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO SWIFT_VERSION=$SWIFT_VERSION | xcpretty
  - bundle exec fastlane test_ci

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Adhan'
