language: swift

osx_image: 
- xcode10.1
- xcode10.2

env:
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.2
- SWIFT_VERSION=5.0

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

matrix:
  exclude:
  - osx_image: xcode10.1
    env: SWIFT_VERSION=5.0

script:
  - bundle exec fastlane test_ci
  - bash <(curl -s https://codecov.io/bash) -J 'Adhan'
  - xcodebuild clean build -scheme 'Adhan-watchOS' -project Adhan.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO SWIFT_VERSION=$SWIFT_VERSION | xcpretty